version: "1.0"
services:
  postgres:
    container_name: "bigdata_snowflake"
    image: postgres:16.4
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mapped:/var/lib/postgresql/data
    ports:
      - "5432:5432"